### ISSUE TITLE
Where do you define MQTT host?

### ISSUE THREAD

**Issue by xbmcnut** [algirdasc/appdaemon-apps#1]
I'm assuming it is expecting the broker on localhost or can this be defined somewhere? I use a broker on a Synology NAS instead. 

Keen to give this a try as it is exactly what I've been looking for.

**Comment by algirdasc** [comment]
Hey. It uses Home Assistant mqtt_publish service, so this AppDaemon app doesn’t know anything about MQTT broker it is using. I’m guessing you’re not using Home Assistant?

**Comment by xbmcnut** [comment]
Of course it does, sorry about that. Long time HA user, first time custom component. Do I need anything in configuration.yaml or just drop .py in custom components folder and restart (after editing camera list)?
